// <auto-generated />
using Infrastructure.MakeupCatalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.MakeupCatalog.Migrations
{
    [DbContext(typeof(MakeupDbContext))]
    [Migration("20220422190443_PopulateDb")]
    partial class PopulateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Domain.MakeupCatalog.MakeupType", b =>
                {
                    b.Property<int>("MakeupTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("MakeupTypeId");

                    b.ToTable("MakeupType");
                });

            modelBuilder.Entity("Domain.MakeupCatalog.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<int>("MakeupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("ProductId");

                    b.HasIndex("MakeupTypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.MakeupCatalog.Product", b =>
                {
                    b.HasOne("Domain.MakeupCatalog.MakeupType", "MakeupType")
                        .WithMany("Product")
                        .HasForeignKey("MakeupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MakeupType");
                });

            modelBuilder.Entity("Domain.MakeupCatalog.MakeupType", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
